version: '2.4'

services:
  bookstore:
    image: bookapp:0.0.1
    ports:
      - 9091:8080
    environment:
      DB_URL: "jdbc:h2:tcp://172.24.0.2:1521/testdb;DB_CLOSE_DELAY=-1"

  h2db:
    image: oscarfonts/h2
    platform: linux/amd64
    ports:
      - 9092:8082