version: '2.4'

services:
  bookstore:
    image: bookapp:0.0.1
    ports:
      - 9091:8080
    environment:
      DB_URL: "jdbc:h2:tcp://h2db/testdb;DB_CLOSE_DELAY=-1"
      DB_USERNAME: "sa"
      DB_PASSWORD: "password"

  h2db:
    image: buildo/h2database
    platform: linux/amd64
    ports:
      - 9092:8082